spring:
  application:
    name: datasource-manage
  datasource:
    url: jdbc:mysql://localhost:3306/market
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /pages/
      suffix: .html

jdbc:
  type: mysql

mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml

server:
  port: 8080


