server:
  port: 18083
  tomcat: uri-encoding:UTF-8

spring:
  application:
    name: merchant-gateway
  http:
    encoding:
      force: true
      enabled: true

security:
  basic:
    enabled: false
