server:
  port: 8080
  tomcat: uri-encoding:UTF-8

spring:
  application:
    name: hermos-core
  http:
    encoding:
      force: true
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/hermes
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

jdbc:
  type: mysql

security:
  basic:
    enabled: false

mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml


